name = "PBN"
version = "0.1.0"
defaultTargets = ["pbn"]

[[lean_lib]]
name = "PBN"

[[lean_exe]]
name = "pbn"
root = "Main"
moreLinkArgs = [
  "-L./rustlib/target/debug",
  "-lrustlib",
  "-Wl,-rpath,@loader_path/../../../../rustlib/target/debug/deps",
  "-L./aonav/target/debug",
  "-Wl,-rpath,@loader_path/../../../../aonav/target/debug/deps"
]

[[require]]
name = "proofwidgets"
scope = "leanprover-community"
rev = "v0.0.100"

[[require]]
name = "aesop"
git = "https://github.com/leanprover-community/aesop"
